change robot drive forward algo
reubenkw/capstone pull request #26
Opened 2024-02-16 19:13 UTC by elinliu2

2024-02-16 23:09 UTC, reubenkw requested changes

2024-02-16 23:09 UTC, reubenkw commented on jetson/src/core/robot.cpp
> +		double goal_orientation = atan2(delta.y, delta.x);
isn't this backwards? `atan 0 = 0` should be the case of `delta.x = 0` and `delta.y` be the distance the robot moves forward

2024-02-16 23:09 UTC, reubenkw commented on jetson/src/core/robot.cpp
> +		double w = angular_error_gain * error_angular;
mod PI and abs?? Im I dumb. How is this gonna work. I think you want the error to be `std::fmod(goal_orientation - robotAngle, 2*M_PI) - M_PI` such that it is between -PI and PI.

2024-02-16 23:09 UTC, reubenkw commented on jetson/src/core/robot.cpp
>  	while (delta.mag() < ROBOT_TOL) {
Not sure what suggestion to make but I'd like to just acknowledge that an overshoot would result in a runaway robot. Or at least a spiraling robot

2024-02-17 00:27 UTC, elinliu2 commented on jetson/src/core/robot.cpp
> +		double goal_orientation = atan2(delta.y, delta.x);
agreed but then i think it should be -x for RHR convention

2024-02-18 18:13 UTC, reubenkw approved these changes

2024-02-19 00:13 UTC, merged