Imaging
reubenkw/capstone pull request #5
Opened 2024-01-14 05:12 UTC by elinliu2

2024-01-23 21:40 UTC, reubenkw requested changes

2024-01-23 21:40 UTC, reubenkw commented on Imaging.cpp
> +	for (int i = 1; i < label_count; i-=-1) {
no.
```suggestion
	for (int i = 1; i < label_count; i+=1) {
```

2024-01-23 21:42 UTC, reubenkw approved these changes

2024-01-24 03:16 UTC, gabeluo approved these changes

2024-01-24 03:16 UTC, merged